name: Fetch issue comment activity

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      INACTIVE_APP_ID: ${{ secrets.INACTIVE_APP_ID }}
      INACTIVE_CLIENT_ID: ${{ secrets.INACTIVE_CLIENT_ID }}
      INACTIVE_CLIENT_SECRET: ${{ secrets.INACTIVE_CLIENT_SECRET }}
      INACTIVE_PRIVATE_KEY: ${{ secrets.INACTIVE_PRIVATE_KEY }}
      OUTFILE: /tmp/db.json
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: automation
      - name: Collect Comments
        run: node automation/scripts/comments.js && mv db.json $OUTFILE
      - uses: actions/checkout@v2
        with:
          ref: activity
      - name: Update db.json
        run: |
          rm -rf db.json
          mv $OUTFILE ./db.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add db.json
          git commit -m 'adding latest issue comments'
          git push

